name: Unit Test on Pull Request

on:
  pull_request:
    branches:      
      - main

jobs:
  unit-test:
    name: ğŸ§ª Testes UnitÃ¡rios
    runs-on: ubuntu-latest

    steps:
      - name:  ğŸ“¥ Checkout do CÃ³digo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 

      - name: â–¶ï¸ Rodar testes
        run: |
          echo "::group::Executando testes unitÃ¡rios"
          mvn test
          echo "::endgroup::"

      - name: ğŸ“Š Gerar badge JaCoCo
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1
      
      - name: ğŸ“ˆ Exibir cobertura
        run: |
          echo "Coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "Branch Coverage = ${{ steps.jacoco.outputs.branches }}"
      
      - name: ğŸ—ƒï¸ Upload do relatÃ³rio JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
